### PR TITLE
Add Composers Play

### PR DESCRIPTION
**Pull request by vlvagerviwager**
Before raising a PR and it getting merged, make sure you have completed the following:

### Things to do:

- [x] Add podcasts in appropriate categories in ascending order of podcast name
- [x] If there is no matching category, add a new category to the list in ascending order of category name, and add it to the table of contents in the same order
- [x] Add a brief description of the podcast
- [x] Add a host of the podcast (optional if hosted by group or panel)
- [x] Add the frequency of episodes (check the list for examples)
- [x] Add the runtime of episodes, giving an approximate range and an average duration

Thanks for your contributions and being awesome :) Cheers.

### CODE REVIEW

**Comment by Smoczysko** [comment]
@vlvagerviwager How does "Composers Play" podcast relate to software development and engineering? From the description you provided ("Listen to a video game composer discuss soundtracks of iconic games (...) often while playing the game" I cannot see the relation.

**Comment by vlvagerviwager** [comment]
@Smoczysko Thanks for your reply, I thought it would be interesting for developers who game or game developers. Feel free to close this.

**Comment by Smoczysko** [comment]
It it interesting, that's for sure. But I think it may be better suited for other repositories. Here's an idea: https://github.com/Calinou/awesome-gamedev#talks

**Comment by vlvagerviwager** [comment]
Cool, will take a look at that repo, thanks!

**Pull request closed without merging**
