### PR TITLE
Fix markdown layout

### PR DESCRIPTION
**Pull request by guar47**
Hi, guys! 

I fixed markdown a bit:
1. Change HTML `<b>` on `**` markdowns bold syntax.
2. Change `-` unsorted list on `*`.
3. Fixed common layout for consistency.

I used [markdownlint](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint} for changing.

Let me know what you think.

### CODE REVIEW

**Comment by rShetty** [comment]
Oops, merge conflicts

**Comment by rShetty** [comment]
Sorry I merged the other one

**Comment by guar47** [comment]
@rShetty don't worry I'll fix them.

**Comment by guar47** [comment]
@rShetty done.

**Comment by rShetty** [comment]
Thanks

**Pull request merged**
