### PR TITLE
Add "Пятиминутка PHP" and "Пятиминутка React" podcasts

### PR DESCRIPTION
**Pull request by pqr**
Before raising a PR and it getting merged, make sure you have completed the following:

### Things to do:

- [X] Add podcasts in appropriate categories in ascending order of podcast name
- [X] If there is no matching category, add a new category to the list in ascending order of category name, and add it to the table of contents in the same order
- [X] Add a brief description of the podcast
- [X] Add the frequency of episodes (Check the list for examples)

Thanks for your contributions and being awesome :) Cheers.

### CODE REVIEW

**Comment by rShetty** [comment]
@saitonakamura Can you help review this PR ?

**Comment by saitonakamura** [comment]
@rShetty Yep, will do

**Comment by saitonakamura** [comment]
Hi @pqr, can you please create a separate categories for JavaScript, react and phone as in main page?

**Comment by saitonakamura** [comment]
@pqr I've updated the categories by myself, I hope you don't mind it

**Pull request merged**
